# Generated by Django 5.1.2 on 2024-10-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartreuse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentType',
            new_name='contentType',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='password',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='url_id',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
