# Generated by Django 5.1.1 on 2024-10-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartreuse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
