# Generated by Django 5.1.1 on 2024-11-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartreuse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100),
        ),
    ]
