# Generated by Django 5.1.1 on 2024-11-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartreuse', '0002_node_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], max_length=100),
        ),
    ]
