# Generated by Django 5.1.2 on 2024-10-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartreuse', '0002_rename_commenttype_comment_contenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubPolling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_polled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chartreuse.comment'),
            preserve_default=False,
        ),
    ]
